language: node_js
node_js:
  - 4
cache:
  directories:
    - node_modules
install: npm install
script: npm run prod
deploy:
  provider: surge
  project: ./build/
  domain: devne.ws
  skip_cleanup: true
